package com.galih.makhrajulhuruf.utils

import com.galih.makhrajulhuruf.R
import com.galih.makhrajulhuruf.data.model.ArabCharacter

val labelList = listOf(
    "Ain_End",
    "Ain_Isolated",
    "Ain_Middle",
    "Ain_Start",
    "Alf_End",
    "Alf_Hamza_Above_End",
    "Alf_Hamza_Above_Isolated",
    "Alf_Hamza_Under_End",
    "Alf_Hamza_Under_Isolated",
    "Alf_Isolated",
    "Baa_End",
    "Baa_Isolated",
    "Baa_Middle",
    "Baa_Start",
    "Daad_End",
    "Daad_Isolated",
    "Daad_Middle",
    "Daad_Start",
    "Dal_End",
    "Dal_Isolated",
    "Faa_End",
    "Faa_Isolated",
    "Faa_Middle",
    "Faa_Start",
    "Gem_End",
    "Gem_Isolated",
    "Gem_Start",
    "Gen_End",
    "Gen_Isolated",
    "Gen_Middle",
    "Haa_End",
    "Haa_Isolated",
    "Haa_Start",
    "Hamza_Isolated",
    "Ha_End",
    "Ha_Isolated",
    "Ha_Middle",
    "Ha_Start",
    "Kaf_End",
    "Kaf_Isolated",
    "Kaf_Middle",
    "Kaf_Start",
    "Khaa_End",
    "Khaa_Isolated",
    "Khaa_Start",
    "Lam_Alf_End",
    "Lam_Alf_Hamza_End",
    "Lam_Alf_Hamza_Isolated",
    "Lam_Alf_Isolated",
    "Lam_Alf_Mad_End",
    "Lam_Alf_Mad_Isolated",
    "Lam_End",
    "Lam_Isolated",
    "Lam_Middle",
    "Lam_Start",
    "Mem_End",
    "Mem_Isolated",
    "Mem_Start",
    "Non_End",
    "Non_Isolated",
    "Non_Middle",
    "Non_Start",
    "Qaf_End",
    "Qaf_Isolated",
    "Qaf_Middle",
    "Qaf_Start",
    "Raa_End",
    "Raa_Isolated",
    "Saad_End",
    "Saad_Isolated",
    "Saad_Middle",
    "Saad_Start",
    "Shen_End",
    "Shen_Isolated",
    "Shen_Middle",
    "Shen_Start",
    "Sin_End",
    "Sin_Isolated",
    "Sin_Middle",
    "Sin_Start",
    "Taa_End",
    "Taa_Isolated",
    "Taa_Middle",
    "Taa_Start",
    "Tah_Isolated",
    "Tah_Middle",
    "Thaa_End",
    "Thaa_Isolated",
    "Thaa_Middle",
    "Thaa_Start",
    "Waw_End",
    "Waw_Hamza_Isolated",
    "Waw_Isolated",
    "Yaa_Dot_End",
    "Yaa_Dot_Isolated",
    "Yaa_Dot_Start",
    "Yaa_End",
    "Yaa_Isolated",
    "Yaa_Middle",
    "Zah_Isolated",
    "Zah_Middle",
    "Zal_End",
    "Zal_Isolated",
    "Zin_End",
    "Zin_Isolated"
)

val characters = listOf(
    ArabCharacter(
        "Alif",
        R.drawable.alif,
        "https://drive.google.com/uc?export=download&id=1AZlXB_53z2CYjU4edtSskJjiKYLaQD3Z",
        "",
        listOf(
            "Alf_End",
            "Alf_Hamza_Above_End",
            "Alf_Hamza_Above_Isolated",
            "Alf_Hamza_Under_End",
            "Alf_Hamza_Under_Isolated",
            "Alf_Isolated",
            "Lam_Alf_End",
            "Lam_Alf_Hamza_End",
            "Lam_Alf_Hamza_Isolated",
            "Lam_Alf_Isolated",
            "Lam_Alf_Mad_End",
            "Lam_Alf_Mad_Isolated",
            "Hamza_Isolated",
        )
    ),
    ArabCharacter(
        "Ba",
        R.drawable.ba,
        "https://drive.google.com/uc?export=download&id=1cm3Zlw-nCSC3JFVKQOzwPpkadyHiN_Ol",
        "",
        listOf(
            "Baa_End",
            "Baa_Isolated",
            "Baa_Middle",
            "Baa_Start",
        )
    ),
    ArabCharacter(
        "Ta",
        R.drawable.ta,
        "https://drive.google.com/uc?export=download&id=1UUqZxcrloQqyhZFsGNO_AFbBE7rIQ-WE",
        "",
        listOf(
            "Taa_End",
            "Taa_Isolated",
            "Taa_Middle",
            "Taa_Start"
        )
    ),
    ArabCharacter(
        "Tsa",
        R.drawable.tsa,
        "https://drive.google.com/uc?export=download&id=1PPmmEZCStcNJnYC1B9vBUCnX7Zi9VqX0",
        "",
        listOf(
            "Thaa_End",
            "Thaa_Isolated",
            "Thaa_Middle",
            "Thaa_Start",
        )
    ),
    ArabCharacter(
        "Jim",
        R.drawable.jim,
        "https://drive.google.com/uc?export=download&id=1FdgfIiYJ0J8H47r7FZ_FhGs5F5DA4hgf",
        "",
        listOf(
            "Gem_End",
            "Gem_Isolated",
            "Gem_Start",
        )
    ),
    ArabCharacter(
        "Ha",
        R.drawable.ha,
        "https://drive.google.com/uc?export=download&id=1YgEZ12HelwO-TrG5zUXZPl6r0nqBF_J2",
        "",
        listOf(
            "Haa_End",
            "Haa_Isolated",
            "Haa_Start",
        )
    ),
    ArabCharacter(
        "Kha",
        R.drawable.kho,
        "https://drive.google.com/uc?export=download&id=1li2ls8ORhnLoREME7o3qYr6QkSPJnBoQ",
        "",
        listOf(
            "Khaa_End",
            "Khaa_Isolated",
            "Khaa_Start",
        )
    ),
    ArabCharacter(
        "Dal",
        R.drawable.dal,
        "https://drive.google.com/uc?export=download&id=1H_PLkFlf8MjysOkrpC6BSEpAkAvXhNpp",
        "",
        listOf(
            "Dal_End",
            "Dal_Isolated",
        )
    ),
    ArabCharacter(
        "Dzal",
        R.drawable.dzal,
        "https://drive.google.com/uc?export=download&id=175Rdil4D9EKQOX_C0OJaDi4_5E5dRggC",
        "",
        listOf(
            "Zal_End",
            "Zal_Isolated",
        )
    ),
    ArabCharacter(
        "Ra",
        R.drawable.ra,
        "https://drive.google.com/uc?export=download&id=1fh1_hdMhmZrf22Q5Q7eTJOG0z3ZWgn6g",
        "",
        listOf(
            "Raa_End",
            "Raa_Isolated",
        )
    ),
    ArabCharacter(
        "Za",
        R.drawable.zain,
        "https://drive.google.com/uc?export=download&id=1C9E2bTGw5qwYTPb_DBaQ0Y6P6Kz_-Wst",
        "",
        listOf(
            "Zin_End",
            "Zin_Isolated"
        )
    ),
    ArabCharacter(
        "Sin",
        R.drawable.sin,
        "https://drive.google.com/uc?export=download&id=1nj-4UjfaHYjz9QBIhdUuTbiSYKm_pRIA",
        "",
        listOf(
            "Sin_End",
            "Sin_Isolated",
            "Sin_Middle",
            "Sin_Start",
        )
    ),
    ArabCharacter(
        "Syin",
        R.drawable.syin,
        "https://drive.google.com/uc?export=download&id=1J1n5FqdugIgfpPFsNL6IrXSJ1GVP5wPx",
        "",
        listOf(
            "Shen_End",
            "Shen_Isolated",
            "Shen_Middle",
            "Shen_Start",
        )
    ),
    ArabCharacter(
        "Shad",
        R.drawable.shad,
        "https://drive.google.com/uc?export=download&id=1rWitITJp_IaEH_j6dMfsd4tax_kIELtk",
        "",
        listOf(
            "Saad_End",
            "Saad_Isolated",
            "Saad_Middle",
            "Saad_Start",
        )
    ),
    ArabCharacter(
        "Dhad",
        R.drawable.dhad,
        "https://drive.google.com/uc?export=download&id=1d52puCB4xxXIyibBTBO7jCfmmtGh_8XA",
        "",
        listOf(
            "Daad_End",
            "Daad_Isolated",
            "Daad_Middle",
            "Daad_Start",
        )
    ),
    ArabCharacter(
        "Tha",
        R.drawable.tha,
        "https://drive.google.com/uc?export=download&id=1ME8Hrub2lTQs_1vUYb97xeM8EX7jlf-D",
        "",
        listOf(
            "Tah_Isolated",
            "Tah_Middle",
        )
    ),
    ArabCharacter(
        "Zha",
        R.drawable.zha,
        "https://drive.google.com/uc?export=download&id=11a7Xy2PCBv9N6jjzhrL4TTXFfVgW2D5p",
        "",
        listOf(
            "Zah_Isolated",
            "Zah_Middle",
        )
    ),
    ArabCharacter(
        "Ain",
        R.drawable.ain,
        "https://drive.google.com/uc?export=download&id=1y_fdaB7wNpVBJxUYmslA9dXTL5RkT6CA",
        "",
        listOf(
            "Ain_End",
            "Ain_Isolated",
            "Ain_Middle",
            "Ain_Start",
        )
    ),
    ArabCharacter(
        "Ghain",
        R.drawable.ghain,
        "https://drive.google.com/uc?export=download&id=1wmkZIBYgT-c69dFxccnQzj_OOLf1fx_3",
        "",
        listOf(
            "Gen_End",
            "Gen_Isolated",
            "Gen_Middle",
        )
    ),
    ArabCharacter(
        "Fa",
        R.drawable.fa,
        "https://drive.google.com/uc?export=download&id=1DdonpOuhkpDf4rjBHVeG0fV4EJC1tUcI",
        "",
        listOf(
            "Faa_End",
            "Faa_Isolated",
            "Faa_Middle",
            "Faa_Start",
        )
    ),
    ArabCharacter(
        "Qaf",
        R.drawable.qaf,
        "https://drive.google.com/uc?export=download&id=14EJiDTNoVQ6N3DnCByyFsXy8Z5mDo61R",
        "",
        listOf(
            "Qaf_End",
            "Qaf_Isolated",
            "Qaf_Middle",
            "Qaf_Start",
        )
    ),
    ArabCharacter(
        "Kaf",
        R.drawable.kaf,
        "https://drive.google.com/uc?export=download&id=1ehXBAe9jZ4bOfDoj36zkbGaHNUV9caZB",
        "",
        listOf(
            "Kaf_End",
            "Kaf_Isolated",
            "Kaf_Middle",
            "Kaf_Start",
        )
    ),
    ArabCharacter(
        "Lam",
        R.drawable.lam,
        "https://drive.google.com/uc?export=download&id=1Jizp9EmN-y8TZmOXmkfbagyIBSyEqHlb",
        "",
        listOf(
            "Lam_End",
            "Lam_Isolated",
            "Lam_Middle",
            "Lam_Start",
            "Lam_Alf_End",
            "Lam_Alf_Hamza_End",
            "Lam_Alf_Hamza_Isolated",
            "Lam_Alf_Isolated",
            "Lam_Alf_Mad_End",
            "Lam_Alf_Mad_Isolated",
        )
    ),
    ArabCharacter(
        "Mim",
        R.drawable.mim,
        "https://drive.google.com/uc?export=download&id=1M17_FDGNrSLESqke-ihI6yCX5BdbUh_P",
        "",
        listOf(
            "Mem_End",
            "Mem_Isolated",
            "Mem_Start",
        )
    ),
    ArabCharacter(
        "Nun",
        R.drawable.nun,
        "https://drive.google.com/uc?export=download&id=19n29koi9ScmKQ4O-8y_b2aw0rmGNtqsa",
        "",
        listOf(
            "Non_End",
            "Non_Isolated",
            "Non_Middle",
            "Non_Start",
        )
    ),
    ArabCharacter(
        "Wau",
        R.drawable.wau,
        "https://drive.google.com/uc?export=download&id=1LeNeb7qQn926qPOhRzgA22cw3D9biroP",
        "",
        listOf(
            "Waw_End",
            "Waw_Hamza_Isolated",
            "Waw_Isolated",
        )
    ),
    ArabCharacter(
        "Ha",
        R.drawable.haa,
        "https://drive.google.com/uc?export=download&id=1X6QJiyPKkYydD0uOIlppQfMDwy8zADje",
        "",
        listOf(
            "Ha_End",
            "Ha_Isolated",
            "Ha_Middle",
            "Ha_Start",
        )
    ),
    ArabCharacter(
        "Ya",
        R.drawable.ya,
        "https://drive.google.com/uc?export=download&id=17XYcLd_dlnc9NtVTZ0oLGf4dY5o3TRNk",
        "",
        listOf(
            "Yaa_Dot_End",
            "Yaa_Dot_Isolated",
            "Yaa_Dot_Start",
            "Yaa_End",
            "Yaa_Isolated",
            "Yaa_Middle",
        )
    )
)